# Generated by Django 4.2.4 on 2023-09-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BlogTecnoWave", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("text", models.CharField(max_length=300)),
            ],
        ),
    ]
